//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/Tests/InputAction/NewActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Tests/InputAction/NewActions.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @NewActions: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @NewActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""NewActions"",
    ""maps"": [
        {
            ""name"": ""纳刀S"",
            ""id"": ""f96860ce-807f-476e-a710-7d14e06b4811"",
            ""actions"": [
                {
                    ""name"": ""移动"",
                    ""type"": ""Value"",
                    ""id"": ""84fa5c33-f48a-49c9-92d5-9ac6dd3ffb05"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""奔跑"",
                    ""type"": ""PassThrough"",
                    ""id"": ""8559f7b4-5f48-4e9d-bf75-efd6b16040b4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""翻滚"",
                    ""type"": ""PassThrough"",
                    ""id"": ""48e909ce-3f27-4178-9652-c3eed2e21e03"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""飞扑"",
                    ""type"": ""Button"",
                    ""id"": ""a82327e0-2a4c-4dd9-a8af-08bcf1814d19"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""拔刀"",
                    ""type"": ""PassThrough"",
                    ""id"": ""7eaef896-b8ad-4796-b72e-f7b3a7ccb8cf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""气刃斩"",
                    ""type"": ""PassThrough"",
                    ""id"": ""4d59852c-a684-45bf-93f7-05b009efe397"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""cc59560d-511c-4e41-860a-1b93887da660"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";gamepad"",
                    ""action"": ""奔跑"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cde13e2d-e2d1-4c21-b4b0-36d1703c7759"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""移动"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4f83b32f-6be0-456d-af13-767a5c8bc9b6"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";gamepad"",
                    ""action"": ""翻滚"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""25e50043-a878-4d83-bc3e-ba5ed164877a"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";gamepad"",
                    ""action"": ""拔刀"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""74c224a7-6c36-47be-b0df-5ac044230b25"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";gamepad"",
                    ""action"": ""气刃斩"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""0e947659-a76f-46f6-93d9-2dea74f3f662"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""飞扑"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""d39b0e8a-ad86-49e6-bbd4-914a797446eb"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";gamepad"",
                    ""action"": ""飞扑"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""802a8738-5e47-4e12-9f0e-3b301af9ba07"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";gamepad"",
                    ""action"": ""飞扑"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""纳刀M"",
            ""id"": ""d94776b0-ed44-4898-a57b-ec358d33c714"",
            ""actions"": [
                {
                    ""name"": ""移动"",
                    ""type"": ""Value"",
                    ""id"": ""e7a56062-5f55-487b-9da0-05d2bbf1a71b"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f82624de-bc3b-4f56-b42d-b18f9adabcc7"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""Clamp(min=-0.5,max=0.5)"",
                    ""groups"": """",
                    ""action"": ""移动"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""拔刀S"",
            ""id"": ""2246e66a-5cc2-427e-bbf9-5acb44945d1c"",
            ""actions"": [
                {
                    ""name"": ""移动"",
                    ""type"": ""Value"",
                    ""id"": ""2d13ca4f-8dc0-418b-9518-64c02efbf07f"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""翻滚"",
                    ""type"": ""PassThrough"",
                    ""id"": ""b756319e-5289-4aa7-844a-b5ee8dacacc8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""纳刀"",
                    ""type"": ""PassThrough"",
                    ""id"": ""7d425744-bf69-41f4-89d5-b79ba0e4d8ba"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""戳"",
                    ""type"": ""PassThrough"",
                    ""id"": ""4250f800-2d64-47de-b356-ef21f5bedbe5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""气刃斩"",
                    ""type"": ""PassThrough"",
                    ""id"": ""8abeed7a-28fa-4c26-a7ee-1cefe2d3cc5f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c4e8ceb6-8b68-47b1-b99d-45d17e3c656c"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";gamepad"",
                    ""action"": ""翻滚"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""012d0b37-47e5-4613-95c2-1e733e88f3dd"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""移动"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fef91485-9db7-4275-b4f2-56c52e202227"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";gamepad"",
                    ""action"": ""纳刀"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5b2a584c-88e2-4f42-8ff7-3465a815df8d"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";gamepad"",
                    ""action"": ""纳刀"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6192cf35-fb54-404a-b6c1-d93feb056665"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";gamepad"",
                    ""action"": ""气刃斩"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0f4aff3e-2414-44a6-aa59-cf34e431c005"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";gamepad"",
                    ""action"": ""戳"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""攻击S"",
            ""id"": ""64602ed9-990c-4d0e-af59-ce2f771e499d"",
            ""actions"": [
                {
                    ""name"": ""方向"",
                    ""type"": ""Value"",
                    ""id"": ""f9513485-ac67-45ed-8ba2-4cdbbda777b2"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""翻滚"",
                    ""type"": ""PassThrough"",
                    ""id"": ""3be9d894-e2a3-4db5-a1d6-e36fc9cc2c74"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""纳刀"",
                    ""type"": ""PassThrough"",
                    ""id"": ""15f91398-8bd5-4420-82bf-de5dad8c7aa2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""戳"",
                    ""type"": ""PassThrough"",
                    ""id"": ""28506d6a-c014-4e42-9d83-bdb40a223eae"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""气刃斩"",
                    ""type"": ""PassThrough"",
                    ""id"": ""fcb3721a-a78d-4c41-a0fd-573d29647e31"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""看破斩"",
                    ""type"": ""PassThrough"",
                    ""id"": ""14213b05-a09a-430e-b8d8-14abb76168c4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""特殊纳刀"",
                    ""type"": ""PassThrough"",
                    ""id"": ""2d863847-06a6-4c7f-9d86-5e245ae0788a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""居合拔刀斩"",
                    ""type"": ""PassThrough"",
                    ""id"": ""2f4b7d0a-b82a-4973-bfe6-0a9eaff5e1b5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""居合拔刀气刃斩"",
                    ""type"": ""PassThrough"",
                    ""id"": ""299ad7af-93b4-418d-a636-e592854084de"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""780fa5aa-1962-49d3-bf0e-16f351c663c3"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";gamepad"",
                    ""action"": ""戳"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""15ed29f8-08ee-45e5-98d3-b2a19d5c8d3c"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";gamepad"",
                    ""action"": ""居合拔刀斩"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fd820530-fb54-451b-9b70-24fe55c131f4"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";gamepad"",
                    ""action"": ""气刃斩"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eccb7fb2-ae15-448e-8851-7dfb076a01ac"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";gamepad"",
                    ""action"": ""居合拔刀气刃斩"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""908740fe-5d1b-43ef-9da2-8abae4c010a8"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";gamepad"",
                    ""action"": ""纳刀"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""975d78bc-db1e-4c54-8726-97b02b9d7fab"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";gamepad"",
                    ""action"": ""纳刀"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fb27ac2d-8981-4192-85c2-3df2770cd739"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";gamepad"",
                    ""action"": ""翻滚"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e4da73e2-812e-4a68-9a68-c9e0e18ce183"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""方向"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""eab977ac-b2db-4e27-b81c-c3da18ec0c4b"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""特殊纳刀"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""f5543fe9-3915-48f4-954f-6af140f98668"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";gamepad"",
                    ""action"": ""特殊纳刀"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""302eb077-d9c8-4706-a51a-c5469f82b0a7"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";gamepad"",
                    ""action"": ""特殊纳刀"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""a0ab45ef-ffa0-4b2c-abd5-66d97fe97d0e"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""看破斩"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""ab7758e8-68dd-47ff-900c-1c0b4e76fe37"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";gamepad"",
                    ""action"": ""看破斩"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""62160819-25e9-4e8b-a410-563f791cc3ab"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";gamepad"",
                    ""action"": ""看破斩"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""gamepad"",
            ""bindingGroup"": ""gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""keyboard"",
            ""bindingGroup"": ""keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // 纳刀S
        m_纳刀S = asset.FindActionMap("纳刀S", throwIfNotFound: true);
        m_纳刀S_移动 = m_纳刀S.FindAction("移动", throwIfNotFound: true);
        m_纳刀S_奔跑 = m_纳刀S.FindAction("奔跑", throwIfNotFound: true);
        m_纳刀S_翻滚 = m_纳刀S.FindAction("翻滚", throwIfNotFound: true);
        m_纳刀S_飞扑 = m_纳刀S.FindAction("飞扑", throwIfNotFound: true);
        m_纳刀S_拔刀 = m_纳刀S.FindAction("拔刀", throwIfNotFound: true);
        m_纳刀S_气刃斩 = m_纳刀S.FindAction("气刃斩", throwIfNotFound: true);
        // 纳刀M
        m_纳刀M = asset.FindActionMap("纳刀M", throwIfNotFound: true);
        m_纳刀M_移动 = m_纳刀M.FindAction("移动", throwIfNotFound: true);
        // 拔刀S
        m_拔刀S = asset.FindActionMap("拔刀S", throwIfNotFound: true);
        m_拔刀S_移动 = m_拔刀S.FindAction("移动", throwIfNotFound: true);
        m_拔刀S_翻滚 = m_拔刀S.FindAction("翻滚", throwIfNotFound: true);
        m_拔刀S_纳刀 = m_拔刀S.FindAction("纳刀", throwIfNotFound: true);
        m_拔刀S_戳 = m_拔刀S.FindAction("戳", throwIfNotFound: true);
        m_拔刀S_气刃斩 = m_拔刀S.FindAction("气刃斩", throwIfNotFound: true);
        // 攻击S
        m_攻击S = asset.FindActionMap("攻击S", throwIfNotFound: true);
        m_攻击S_方向 = m_攻击S.FindAction("方向", throwIfNotFound: true);
        m_攻击S_翻滚 = m_攻击S.FindAction("翻滚", throwIfNotFound: true);
        m_攻击S_纳刀 = m_攻击S.FindAction("纳刀", throwIfNotFound: true);
        m_攻击S_戳 = m_攻击S.FindAction("戳", throwIfNotFound: true);
        m_攻击S_气刃斩 = m_攻击S.FindAction("气刃斩", throwIfNotFound: true);
        m_攻击S_看破斩 = m_攻击S.FindAction("看破斩", throwIfNotFound: true);
        m_攻击S_特殊纳刀 = m_攻击S.FindAction("特殊纳刀", throwIfNotFound: true);
        m_攻击S_居合拔刀斩 = m_攻击S.FindAction("居合拔刀斩", throwIfNotFound: true);
        m_攻击S_居合拔刀气刃斩 = m_攻击S.FindAction("居合拔刀气刃斩", throwIfNotFound: true);
    }

    ~@NewActions()
    {
        UnityEngine.Debug.Assert(!m_纳刀S.enabled, "This will cause a leak and performance issues, NewActions.纳刀S.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_纳刀M.enabled, "This will cause a leak and performance issues, NewActions.纳刀M.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_拔刀S.enabled, "This will cause a leak and performance issues, NewActions.拔刀S.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_攻击S.enabled, "This will cause a leak and performance issues, NewActions.攻击S.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // 纳刀S
    private readonly InputActionMap m_纳刀S;
    private List<I纳刀SActions> m_纳刀SActionsCallbackInterfaces = new List<I纳刀SActions>();
    private readonly InputAction m_纳刀S_移动;
    private readonly InputAction m_纳刀S_奔跑;
    private readonly InputAction m_纳刀S_翻滚;
    private readonly InputAction m_纳刀S_飞扑;
    private readonly InputAction m_纳刀S_拔刀;
    private readonly InputAction m_纳刀S_气刃斩;
    /// <summary>
    /// Provides access to input actions defined in input action map "纳刀S".
    /// </summary>
    public struct 纳刀SActions
    {
        private @NewActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public 纳刀SActions(@NewActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "纳刀S/移动".
        /// </summary>
        public InputAction @移动 => m_Wrapper.m_纳刀S_移动;
        /// <summary>
        /// Provides access to the underlying input action "纳刀S/奔跑".
        /// </summary>
        public InputAction @奔跑 => m_Wrapper.m_纳刀S_奔跑;
        /// <summary>
        /// Provides access to the underlying input action "纳刀S/翻滚".
        /// </summary>
        public InputAction @翻滚 => m_Wrapper.m_纳刀S_翻滚;
        /// <summary>
        /// Provides access to the underlying input action "纳刀S/飞扑".
        /// </summary>
        public InputAction @飞扑 => m_Wrapper.m_纳刀S_飞扑;
        /// <summary>
        /// Provides access to the underlying input action "纳刀S/拔刀".
        /// </summary>
        public InputAction @拔刀 => m_Wrapper.m_纳刀S_拔刀;
        /// <summary>
        /// Provides access to the underlying input action "纳刀S/气刃斩".
        /// </summary>
        public InputAction @气刃斩 => m_Wrapper.m_纳刀S_气刃斩;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_纳刀S; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="纳刀SActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(纳刀SActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="纳刀SActions" />
        public void AddCallbacks(I纳刀SActions instance)
        {
            if (instance == null || m_Wrapper.m_纳刀SActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_纳刀SActionsCallbackInterfaces.Add(instance);
            @移动.started += instance.On移动;
            @移动.performed += instance.On移动;
            @移动.canceled += instance.On移动;
            @奔跑.started += instance.On奔跑;
            @奔跑.performed += instance.On奔跑;
            @奔跑.canceled += instance.On奔跑;
            @翻滚.started += instance.On翻滚;
            @翻滚.performed += instance.On翻滚;
            @翻滚.canceled += instance.On翻滚;
            @飞扑.started += instance.On飞扑;
            @飞扑.performed += instance.On飞扑;
            @飞扑.canceled += instance.On飞扑;
            @拔刀.started += instance.On拔刀;
            @拔刀.performed += instance.On拔刀;
            @拔刀.canceled += instance.On拔刀;
            @气刃斩.started += instance.On气刃斩;
            @气刃斩.performed += instance.On气刃斩;
            @气刃斩.canceled += instance.On气刃斩;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="纳刀SActions" />
        private void UnregisterCallbacks(I纳刀SActions instance)
        {
            @移动.started -= instance.On移动;
            @移动.performed -= instance.On移动;
            @移动.canceled -= instance.On移动;
            @奔跑.started -= instance.On奔跑;
            @奔跑.performed -= instance.On奔跑;
            @奔跑.canceled -= instance.On奔跑;
            @翻滚.started -= instance.On翻滚;
            @翻滚.performed -= instance.On翻滚;
            @翻滚.canceled -= instance.On翻滚;
            @飞扑.started -= instance.On飞扑;
            @飞扑.performed -= instance.On飞扑;
            @飞扑.canceled -= instance.On飞扑;
            @拔刀.started -= instance.On拔刀;
            @拔刀.performed -= instance.On拔刀;
            @拔刀.canceled -= instance.On拔刀;
            @气刃斩.started -= instance.On气刃斩;
            @气刃斩.performed -= instance.On气刃斩;
            @气刃斩.canceled -= instance.On气刃斩;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="纳刀SActions.UnregisterCallbacks(I纳刀SActions)" />.
        /// </summary>
        /// <seealso cref="纳刀SActions.UnregisterCallbacks(I纳刀SActions)" />
        public void RemoveCallbacks(I纳刀SActions instance)
        {
            if (m_Wrapper.m_纳刀SActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="纳刀SActions.AddCallbacks(I纳刀SActions)" />
        /// <seealso cref="纳刀SActions.RemoveCallbacks(I纳刀SActions)" />
        /// <seealso cref="纳刀SActions.UnregisterCallbacks(I纳刀SActions)" />
        public void SetCallbacks(I纳刀SActions instance)
        {
            foreach (var item in m_Wrapper.m_纳刀SActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_纳刀SActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="纳刀SActions" /> instance referencing this action map.
    /// </summary>
    public 纳刀SActions @纳刀S => new 纳刀SActions(this);

    // 纳刀M
    private readonly InputActionMap m_纳刀M;
    private List<I纳刀MActions> m_纳刀MActionsCallbackInterfaces = new List<I纳刀MActions>();
    private readonly InputAction m_纳刀M_移动;
    /// <summary>
    /// Provides access to input actions defined in input action map "纳刀M".
    /// </summary>
    public struct 纳刀MActions
    {
        private @NewActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public 纳刀MActions(@NewActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "纳刀M/移动".
        /// </summary>
        public InputAction @移动 => m_Wrapper.m_纳刀M_移动;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_纳刀M; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="纳刀MActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(纳刀MActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="纳刀MActions" />
        public void AddCallbacks(I纳刀MActions instance)
        {
            if (instance == null || m_Wrapper.m_纳刀MActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_纳刀MActionsCallbackInterfaces.Add(instance);
            @移动.started += instance.On移动;
            @移动.performed += instance.On移动;
            @移动.canceled += instance.On移动;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="纳刀MActions" />
        private void UnregisterCallbacks(I纳刀MActions instance)
        {
            @移动.started -= instance.On移动;
            @移动.performed -= instance.On移动;
            @移动.canceled -= instance.On移动;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="纳刀MActions.UnregisterCallbacks(I纳刀MActions)" />.
        /// </summary>
        /// <seealso cref="纳刀MActions.UnregisterCallbacks(I纳刀MActions)" />
        public void RemoveCallbacks(I纳刀MActions instance)
        {
            if (m_Wrapper.m_纳刀MActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="纳刀MActions.AddCallbacks(I纳刀MActions)" />
        /// <seealso cref="纳刀MActions.RemoveCallbacks(I纳刀MActions)" />
        /// <seealso cref="纳刀MActions.UnregisterCallbacks(I纳刀MActions)" />
        public void SetCallbacks(I纳刀MActions instance)
        {
            foreach (var item in m_Wrapper.m_纳刀MActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_纳刀MActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="纳刀MActions" /> instance referencing this action map.
    /// </summary>
    public 纳刀MActions @纳刀M => new 纳刀MActions(this);

    // 拔刀S
    private readonly InputActionMap m_拔刀S;
    private List<I拔刀SActions> m_拔刀SActionsCallbackInterfaces = new List<I拔刀SActions>();
    private readonly InputAction m_拔刀S_移动;
    private readonly InputAction m_拔刀S_翻滚;
    private readonly InputAction m_拔刀S_纳刀;
    private readonly InputAction m_拔刀S_戳;
    private readonly InputAction m_拔刀S_气刃斩;
    /// <summary>
    /// Provides access to input actions defined in input action map "拔刀S".
    /// </summary>
    public struct 拔刀SActions
    {
        private @NewActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public 拔刀SActions(@NewActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "拔刀S/移动".
        /// </summary>
        public InputAction @移动 => m_Wrapper.m_拔刀S_移动;
        /// <summary>
        /// Provides access to the underlying input action "拔刀S/翻滚".
        /// </summary>
        public InputAction @翻滚 => m_Wrapper.m_拔刀S_翻滚;
        /// <summary>
        /// Provides access to the underlying input action "拔刀S/纳刀".
        /// </summary>
        public InputAction @纳刀 => m_Wrapper.m_拔刀S_纳刀;
        /// <summary>
        /// Provides access to the underlying input action "拔刀S/戳".
        /// </summary>
        public InputAction @戳 => m_Wrapper.m_拔刀S_戳;
        /// <summary>
        /// Provides access to the underlying input action "拔刀S/气刃斩".
        /// </summary>
        public InputAction @气刃斩 => m_Wrapper.m_拔刀S_气刃斩;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_拔刀S; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="拔刀SActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(拔刀SActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="拔刀SActions" />
        public void AddCallbacks(I拔刀SActions instance)
        {
            if (instance == null || m_Wrapper.m_拔刀SActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_拔刀SActionsCallbackInterfaces.Add(instance);
            @移动.started += instance.On移动;
            @移动.performed += instance.On移动;
            @移动.canceled += instance.On移动;
            @翻滚.started += instance.On翻滚;
            @翻滚.performed += instance.On翻滚;
            @翻滚.canceled += instance.On翻滚;
            @纳刀.started += instance.On纳刀;
            @纳刀.performed += instance.On纳刀;
            @纳刀.canceled += instance.On纳刀;
            @戳.started += instance.On戳;
            @戳.performed += instance.On戳;
            @戳.canceled += instance.On戳;
            @气刃斩.started += instance.On气刃斩;
            @气刃斩.performed += instance.On气刃斩;
            @气刃斩.canceled += instance.On气刃斩;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="拔刀SActions" />
        private void UnregisterCallbacks(I拔刀SActions instance)
        {
            @移动.started -= instance.On移动;
            @移动.performed -= instance.On移动;
            @移动.canceled -= instance.On移动;
            @翻滚.started -= instance.On翻滚;
            @翻滚.performed -= instance.On翻滚;
            @翻滚.canceled -= instance.On翻滚;
            @纳刀.started -= instance.On纳刀;
            @纳刀.performed -= instance.On纳刀;
            @纳刀.canceled -= instance.On纳刀;
            @戳.started -= instance.On戳;
            @戳.performed -= instance.On戳;
            @戳.canceled -= instance.On戳;
            @气刃斩.started -= instance.On气刃斩;
            @气刃斩.performed -= instance.On气刃斩;
            @气刃斩.canceled -= instance.On气刃斩;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="拔刀SActions.UnregisterCallbacks(I拔刀SActions)" />.
        /// </summary>
        /// <seealso cref="拔刀SActions.UnregisterCallbacks(I拔刀SActions)" />
        public void RemoveCallbacks(I拔刀SActions instance)
        {
            if (m_Wrapper.m_拔刀SActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="拔刀SActions.AddCallbacks(I拔刀SActions)" />
        /// <seealso cref="拔刀SActions.RemoveCallbacks(I拔刀SActions)" />
        /// <seealso cref="拔刀SActions.UnregisterCallbacks(I拔刀SActions)" />
        public void SetCallbacks(I拔刀SActions instance)
        {
            foreach (var item in m_Wrapper.m_拔刀SActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_拔刀SActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="拔刀SActions" /> instance referencing this action map.
    /// </summary>
    public 拔刀SActions @拔刀S => new 拔刀SActions(this);

    // 攻击S
    private readonly InputActionMap m_攻击S;
    private List<I攻击SActions> m_攻击SActionsCallbackInterfaces = new List<I攻击SActions>();
    private readonly InputAction m_攻击S_方向;
    private readonly InputAction m_攻击S_翻滚;
    private readonly InputAction m_攻击S_纳刀;
    private readonly InputAction m_攻击S_戳;
    private readonly InputAction m_攻击S_气刃斩;
    private readonly InputAction m_攻击S_看破斩;
    private readonly InputAction m_攻击S_特殊纳刀;
    private readonly InputAction m_攻击S_居合拔刀斩;
    private readonly InputAction m_攻击S_居合拔刀气刃斩;
    /// <summary>
    /// Provides access to input actions defined in input action map "攻击S".
    /// </summary>
    public struct 攻击SActions
    {
        private @NewActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public 攻击SActions(@NewActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "攻击S/方向".
        /// </summary>
        public InputAction @方向 => m_Wrapper.m_攻击S_方向;
        /// <summary>
        /// Provides access to the underlying input action "攻击S/翻滚".
        /// </summary>
        public InputAction @翻滚 => m_Wrapper.m_攻击S_翻滚;
        /// <summary>
        /// Provides access to the underlying input action "攻击S/纳刀".
        /// </summary>
        public InputAction @纳刀 => m_Wrapper.m_攻击S_纳刀;
        /// <summary>
        /// Provides access to the underlying input action "攻击S/戳".
        /// </summary>
        public InputAction @戳 => m_Wrapper.m_攻击S_戳;
        /// <summary>
        /// Provides access to the underlying input action "攻击S/气刃斩".
        /// </summary>
        public InputAction @气刃斩 => m_Wrapper.m_攻击S_气刃斩;
        /// <summary>
        /// Provides access to the underlying input action "攻击S/看破斩".
        /// </summary>
        public InputAction @看破斩 => m_Wrapper.m_攻击S_看破斩;
        /// <summary>
        /// Provides access to the underlying input action "攻击S/特殊纳刀".
        /// </summary>
        public InputAction @特殊纳刀 => m_Wrapper.m_攻击S_特殊纳刀;
        /// <summary>
        /// Provides access to the underlying input action "攻击S/居合拔刀斩".
        /// </summary>
        public InputAction @居合拔刀斩 => m_Wrapper.m_攻击S_居合拔刀斩;
        /// <summary>
        /// Provides access to the underlying input action "攻击S/居合拔刀气刃斩".
        /// </summary>
        public InputAction @居合拔刀气刃斩 => m_Wrapper.m_攻击S_居合拔刀气刃斩;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_攻击S; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="攻击SActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(攻击SActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="攻击SActions" />
        public void AddCallbacks(I攻击SActions instance)
        {
            if (instance == null || m_Wrapper.m_攻击SActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_攻击SActionsCallbackInterfaces.Add(instance);
            @方向.started += instance.On方向;
            @方向.performed += instance.On方向;
            @方向.canceled += instance.On方向;
            @翻滚.started += instance.On翻滚;
            @翻滚.performed += instance.On翻滚;
            @翻滚.canceled += instance.On翻滚;
            @纳刀.started += instance.On纳刀;
            @纳刀.performed += instance.On纳刀;
            @纳刀.canceled += instance.On纳刀;
            @戳.started += instance.On戳;
            @戳.performed += instance.On戳;
            @戳.canceled += instance.On戳;
            @气刃斩.started += instance.On气刃斩;
            @气刃斩.performed += instance.On气刃斩;
            @气刃斩.canceled += instance.On气刃斩;
            @看破斩.started += instance.On看破斩;
            @看破斩.performed += instance.On看破斩;
            @看破斩.canceled += instance.On看破斩;
            @特殊纳刀.started += instance.On特殊纳刀;
            @特殊纳刀.performed += instance.On特殊纳刀;
            @特殊纳刀.canceled += instance.On特殊纳刀;
            @居合拔刀斩.started += instance.On居合拔刀斩;
            @居合拔刀斩.performed += instance.On居合拔刀斩;
            @居合拔刀斩.canceled += instance.On居合拔刀斩;
            @居合拔刀气刃斩.started += instance.On居合拔刀气刃斩;
            @居合拔刀气刃斩.performed += instance.On居合拔刀气刃斩;
            @居合拔刀气刃斩.canceled += instance.On居合拔刀气刃斩;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="攻击SActions" />
        private void UnregisterCallbacks(I攻击SActions instance)
        {
            @方向.started -= instance.On方向;
            @方向.performed -= instance.On方向;
            @方向.canceled -= instance.On方向;
            @翻滚.started -= instance.On翻滚;
            @翻滚.performed -= instance.On翻滚;
            @翻滚.canceled -= instance.On翻滚;
            @纳刀.started -= instance.On纳刀;
            @纳刀.performed -= instance.On纳刀;
            @纳刀.canceled -= instance.On纳刀;
            @戳.started -= instance.On戳;
            @戳.performed -= instance.On戳;
            @戳.canceled -= instance.On戳;
            @气刃斩.started -= instance.On气刃斩;
            @气刃斩.performed -= instance.On气刃斩;
            @气刃斩.canceled -= instance.On气刃斩;
            @看破斩.started -= instance.On看破斩;
            @看破斩.performed -= instance.On看破斩;
            @看破斩.canceled -= instance.On看破斩;
            @特殊纳刀.started -= instance.On特殊纳刀;
            @特殊纳刀.performed -= instance.On特殊纳刀;
            @特殊纳刀.canceled -= instance.On特殊纳刀;
            @居合拔刀斩.started -= instance.On居合拔刀斩;
            @居合拔刀斩.performed -= instance.On居合拔刀斩;
            @居合拔刀斩.canceled -= instance.On居合拔刀斩;
            @居合拔刀气刃斩.started -= instance.On居合拔刀气刃斩;
            @居合拔刀气刃斩.performed -= instance.On居合拔刀气刃斩;
            @居合拔刀气刃斩.canceled -= instance.On居合拔刀气刃斩;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="攻击SActions.UnregisterCallbacks(I攻击SActions)" />.
        /// </summary>
        /// <seealso cref="攻击SActions.UnregisterCallbacks(I攻击SActions)" />
        public void RemoveCallbacks(I攻击SActions instance)
        {
            if (m_Wrapper.m_攻击SActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="攻击SActions.AddCallbacks(I攻击SActions)" />
        /// <seealso cref="攻击SActions.RemoveCallbacks(I攻击SActions)" />
        /// <seealso cref="攻击SActions.UnregisterCallbacks(I攻击SActions)" />
        public void SetCallbacks(I攻击SActions instance)
        {
            foreach (var item in m_Wrapper.m_攻击SActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_攻击SActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="攻击SActions" /> instance referencing this action map.
    /// </summary>
    public 攻击SActions @攻击S => new 攻击SActions(this);
    private int m_gamepadSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme gamepadScheme
    {
        get
        {
            if (m_gamepadSchemeIndex == -1) m_gamepadSchemeIndex = asset.FindControlSchemeIndex("gamepad");
            return asset.controlSchemes[m_gamepadSchemeIndex];
        }
    }
    private int m_keyboardSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme keyboardScheme
    {
        get
        {
            if (m_keyboardSchemeIndex == -1) m_keyboardSchemeIndex = asset.FindControlSchemeIndex("keyboard");
            return asset.controlSchemes[m_keyboardSchemeIndex];
        }
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "纳刀S" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="纳刀SActions.AddCallbacks(I纳刀SActions)" />
    /// <seealso cref="纳刀SActions.RemoveCallbacks(I纳刀SActions)" />
    public interface I纳刀SActions
    {
        /// <summary>
        /// Method invoked when associated input action "移动" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On移动(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "奔跑" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On奔跑(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "翻滚" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On翻滚(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "飞扑" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On飞扑(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "拔刀" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On拔刀(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "气刃斩" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On气刃斩(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "纳刀M" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="纳刀MActions.AddCallbacks(I纳刀MActions)" />
    /// <seealso cref="纳刀MActions.RemoveCallbacks(I纳刀MActions)" />
    public interface I纳刀MActions
    {
        /// <summary>
        /// Method invoked when associated input action "移动" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On移动(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "拔刀S" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="拔刀SActions.AddCallbacks(I拔刀SActions)" />
    /// <seealso cref="拔刀SActions.RemoveCallbacks(I拔刀SActions)" />
    public interface I拔刀SActions
    {
        /// <summary>
        /// Method invoked when associated input action "移动" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On移动(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "翻滚" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On翻滚(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "纳刀" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On纳刀(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "戳" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On戳(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "气刃斩" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On气刃斩(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "攻击S" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="攻击SActions.AddCallbacks(I攻击SActions)" />
    /// <seealso cref="攻击SActions.RemoveCallbacks(I攻击SActions)" />
    public interface I攻击SActions
    {
        /// <summary>
        /// Method invoked when associated input action "方向" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On方向(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "翻滚" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On翻滚(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "纳刀" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On纳刀(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "戳" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On戳(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "气刃斩" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On气刃斩(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "看破斩" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On看破斩(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "特殊纳刀" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On特殊纳刀(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "居合拔刀斩" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On居合拔刀斩(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "居合拔刀气刃斩" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On居合拔刀气刃斩(InputAction.CallbackContext context);
    }
}
